# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: CheckURLTool

env:
  - GO111MODULE=on

before:
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    hooks:
      post: cp UrlListToTest.txt urlCheckConfig.json {{ dir .Path }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    wrap_in_directory: true
    files:
      - README.md
      - urlCheckConfig.json
      - UrlListToTest.txt
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
    
