name: CheckURL Tool CI

on:
  push:
    branches: [ TestTool ]
  pull_request:
    branches: [ master ]

jobs:

  # linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Go
  #     uses: actions/setup-go@v2.1.3
  #     with:
  #       go-version: 1.16
      
  #   - name: Build for Linux
  #     run: |
  #      export GO111MODULE=auto
  #      go build -o CheckURL-Linux
    
  #   - name: Wrap files for upload
  #     shell: bash 
  #     run: | 
  #      mkdir ForUpload
  #      cp CheckURL-Linux urlCheckConfig.json UrlListToTest.txt ForUpload/
    
  #   - name: Upload a Build Artifact
  #     uses: actions/upload-artifact@v2.2.4
  #     with:
  #       name: CheckURL-Linux 
  #       path: ForUpload
  #       retention-days: 7
      
        
  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
      
    - name: Build for OSX
      shell: bash
      run: |
       mkdir ForUpload
       export GO111MODULE=auto
       go build -o ForUpload/CheckURL.osx

    - name: Build for Linux
      shell: bash
      run: | 
       GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o ForUpload/CheckURL.linux
    
    - name: Wrap files for upload
      shell: bash 
      run: | 
       cp urlCheckConfig.json UrlListToTest.txt ForUpload/

    - name: Make tar balls
      shell: bash
      run: | 
        cd ForUpload
        tar -czvf urlCheckConfig.json UrlListToTest.txt CheckURL.osx
        tar -czvf urlCheckConfig.json UrlListToTest.txt CheckURL.linux

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: CheckURL.osx 
        path: |
          ForUpload/urlCheckConfig.json
          ForUpload/UrlListToTest.txt
          ForUpload/CheckURL.osx
        retention-days: 7

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: CheckURL.Linux 
        path: |
          ForUpload/urlCheckConfig.json
          ForUpload/UrlListToTest.txt
          ForUpload/CheckURL.linux
        retention-days: 7
