name: CheckURL Tool CI

env: 
  osxFolder: "CheckURL_osx"
  linuxFolder: "CheckURL_linux"
   
on:
  push:
    branches: [ TestTool ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  CheckURL_Tool:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
      
    - name: Build for OSX
      shell: bash
      run: |
       export GO111MODULE=auto
       go build -o $osxFolder/CheckURL-osx
       chmod +x $osxFolder/CheckURL-osx

    - name: Build for Linux
      shell: bash
      run: | 
       export GO111MODULE=auto
       GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o $linuxFolder/CheckURL-linux
       chmod +x $linuxFolder/CheckURL-linux

    - name: Tar ball for OSX
      run: |
        cp urlCheckConfig.json UrlListToTest.txt $osxFolder/ 
        cp urlCheckConfig.json UrlListToTest.txt $linuxFolder/ 
        tar -czvf CheckURL-osx.tar.gz $osxFolder/
        tar -czvf CheckURL-linux.tar.gz $linuxFolder/
  
    - name: 'Upload Darwin Artifact'
      uses: actions/upload-artifact@v2
      with:
       name: CheckURL-osx.tar.gz
       path: CheckURL-osx.tar.gz  
       retention-days: 7

    - name: 'Upload Linux Artifact'
      uses: actions/upload-artifact@v2
      with:
       name: CheckURL-linux.tar.gz
       path: CheckURL-linux.tar.gz   
       retention-days: 7

    - name: Create release draft
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release_draft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: ${{github.ref}}
        draft: true
        prerelease: false

    - name: Upload Release Linux
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.create_release_draft.outputs.upload_url}}
        asset_path: ./CheckURL-linux.tar.gz #${{env.GIT_TAG}}.linux-amd64.tar.gz
        asset_name: CheckURL${{env.GIT_TAG}}.linux-amd64.tar.gz
        asset_content_type: application/gzip; charset=binary

    - name: Upload Release OSX
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.create_release_draft.outputs.upload_url}}
        asset_path: ./CheckURL-osx.tar.gz #${{env.GIT_TAG}}.linux-amd64.tar.gz
        asset_name: CheckURL${{env.GIT_TAG}}.darwin-amd64.tar.gz
        asset_content_type: application/gzip; charset=binary
