name: CheckURL Tool CI

on:
  push:
    branches:
       - master
       - TestTool
  pull_request:
    branches:
       - master

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16
      
    #- name: Build for Linux
    #  run: |
    #   export GO111MODULE=auto
    #   go build -o CheckURL-Linux
    - name: Run GoReleaser
      #if: startsWith(github.ref, 'refs/tags/')
      uses: goreleaser/goreleaser-action@v2            
      with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Wrap files for upload
    #  shell: bash 
    #  run: | 
    #   mkdir ForUpload
    #   cp CheckURL-Linux urlCheckConfig.json UrlListToTest.txt ForUpload/
    
    #- name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v2.2.4
    #  with:
    #    name: CheckURL-Linux 
    #    path: ForUpload
    #    retention-days: 14
    - name: Upload assets
      uses: actions/upload-artifact@v2
      with:
        name: CheckURLTool
        path: dist/*
